version: "3"

services:
  db:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis
    volumes:
      - ./data/db:/data
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_DB=0
